.\" Manpage for jellyfin-rpc.
.\" Contact ben@iipython.dev to correct errors or typos.
.TH jellyfin-rpc 1 "23 May 2024" "1.0" "jellyfin-rpc man page"
.SH NAME
jellfin-rpc \- Jellyfin Music RPC for Discord
.SH SYNOPSIS
jellyfin-rpc
.SH DESCRIPTION
This is a Python app that displays the currently playing song from Jellyfin (or Feishin) on your discord profile.
.SH OPTIONS
The jellyfin-rpc.py script does not take any options. However you should supply configuration file at 
.I /etc/jellyfin-rpc.toml 
or 
.I ~/.config/iipython/jellyfin-rpc.toml
.SH BUGS
No known bugs.
.SH AUTHOR
iiPython (ben@iipython.dev)
